# .github/workflows/generate-images.yml
name: Generate Weekly Calendar Image

on:
  workflow_dispatch:
  # Run every Monday at 17:49 UTC
  schedule:
    - cron: "58 17 * * MON" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator script
        run: |
          python main.py
         

      - name: Commit generated images
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f output/*.png
          git add readme.md


          if ! git diff --cached --quiet; then
            git commit -m "Add weekly calendar image: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
